### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by brunac279** [reskit/moodle-tiny_c4l#6]
Hi, we are having problems displaying the plugin window in Moodle 4.1.

Some parts are being cut, as shown in the image.

![c4l](https://github.com/reskit/moodle-tiny_c4l/assets/61990212/f6d920e7-b4c5-4abf-85a4-5458327ed2ed)

Thank you!

**Comment by brunac279** [comment]
The problem was related to the theme used in Moodle.

**Comment by reskit** [comment]
Hi @brunac279 ,

Thanks for reporting the issue and providing a fix.

Our plugin is working fine with standard themes like Classic and Boost, we've tested it with other popular themes like Moove and Adaptable with no issues.

Your problem seems to be related to Lambda theme which is not free. We don't fix bugs related to paid themes because we can't test them.

I hope you understand our position in this issue.

Cheers
